### ISSUE TITLE
[BUG]  \\ becomes \.

### ISSUE THREAD

**Issue by ddff12** [npm/ini#91] opened 2019-10-29 11:22 UTC
config.ini
```
path= \\server\test\001
```

```
let config = ini.parse(fs.readFileSync('./config.ini', 'utf-8'))

 // config.path → "\server\test\001"
 //  There is only one ’\’ at the beginning of the character.
// But there are two correctly. 
```

**Comment by butakovmv** [comment] 2020-02-18 16:48
It is not bug of this package, it is feature of JavaScript.
Try it: `console.log("\\");`
It'll output `\`
Details is here: https://www.w3schools.com/js/js_strings.asp, see "backslash escape character"

Issue should be closed)

**Comment by m417z** [comment] 2022-03-17 21:43
You can try my fork, [ini-win](https://www.npmjs.com/package/ini-win), which aims to be more compatible with the way Windows handles ini files. Windows doesn't do any unescaping when reading the values, and so does my fork, so it fixes this issue.

**Comment by wraithgar** [comment] 2022-08-17 19:00
Duplicate of #30

**Closed by wraithgar** 2022-08-17 19:00 UTC
